#!/usr/bin/env python3
import sys
import subprocess
import getch

args = sys.argv[:]
args[0] = "sh"

if len(args) == 1:
    print(args)
    sleep(1)
    print("Debug session")
    args = input().split(' ')
    rc = subprocess.Popen(args, stdout=subprocess.PIPE, universal_newlines=True)
    for line in rc.stdout:
        if "/usr/bin/gdb" not in line:
            print(line)
    print("Press any key to continue...")
    getch.getch()
    sys.exit(0)
else:
    print(args)
    sleep(1)
    rc = subprocess.call(args)
    sys.exit(0)
